#! /bin/bash
# los numeros de fibonacci son una secuencia de numeros en la cual
#cada numero sucesivo es la suma de los dos anteriores 1,1,2,3,5,8,13,21,34
fib0=1
fib1=1
echo -n $fib0 " "
echo -n $fib1 " "
n=$1
i=1
while [ $i -lt $n ]
do
  fib=` expr $fib0 + $fib1 `
  echo -n $fib " "
  fib0=$fib1   
  fib1=$fib  
  i=` expr $i + 1 `
done
echo 


